name: fresh_hub_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
      sdk: flutter
  flutter_calendar: ^0.0.8
  flutter_calendar_carousel: ^1.3.7
  google_maps_flutter: ^0.5.2
  url_launcher: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  #plugin:
      #androidPackage: io.flutter.plugins.googlemaps
      #iosPrefix: FLT
      #pluginClass: GoogleMapsPlugin

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/produce.jpg
    - assets/images/sunnyside1-1.jpg
    - assets/images/sunnyside1-2.jpg
    - assets/images/sunnyside1-3.jpg
    - assets/images/sunnyside1-4.jpg
    - assets/images/kashmere1-1.jpg
    - assets/images/kashmere1-2.jpg
    - assets/images/kashmere1-3.jpg
    - assets/images/kashmere1-4.jpg
    - assets/images/kashmere2-1.jpg
    - assets/images/kashmere2-2.png
    - assets/images/kashmere2-3.jpg
    - assets/images/sunnyside2-1.jpg
    - assets/images/sunnyside2-2.jpg
    - assets/images/sunnyside2-3.jpg
    - assets/images/sunnyside2-4.jpg
    - assets/images/foodrescue1-1.jpg
    - assets/images/foodrescue1-2.jpg
    - assets/images/foodrescue1-3.jpg
    - assets/images/foodrescue1-4.jpg
    - assets/images/foodrescue2-1.jpg
    - assets/images/foodrescue2-3.jpg
    - assets/images/foodrescue2-4.jpg
    - assets/images/foodrescue2-5.jpg
    - assets/images/grouppic.jpg
    - assets/images/grouppic2.jpg
    - assets/images/NutritionLabel.jpg
    - assets/images/FoodGroups2.jpg
    - assets/images/FoodPlate.png
    - load_json/appetizers.json
    - load_json/maincourses.json
    - load_json/deserts.json
    - assets/images/sunnyside3-1.jpg
    - assets/images/sunnyside3-2.jpg
    - assets/images/sunnyside3-3.jpg
    - assets/images/sunnyside4-1.jpg
    - assets/images/sunnyside4-2.jpg
    - assets/images/sunnyside4-3.jpg
    - assets/images/kashmere3-1.jpg
    - assets/images/kashmere3-2.jpg
    - assets/images/kashmere3-3.jpg
    - assets/images/kashmere4-1.jpg
    - assets/images/kashmere4-2.jpg
    - assets/images/kashmere4-3.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Abril Fatface
        fonts:
          - asset: fonts/AbrilFatface-Regular.ttf
      - family: Questrial
        fonts:
          - asset: fonts/Questrial-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
